########################### NETWORKS
networks:
  media-management:
    external: true
  qbittorrent:
    external: true

########################### VOLUMES
volumes:
  qbittorrent.etc:
  qbittorrent.var:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.20.200,soft,nfsvers=4"
      device: ":/Media"
  gluetun:

########################### LOCKDOWN
x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

########################### SERVICES
services:
  qbittorrent:
    image: 11notes/qbittorrent:${QBITTORRENT_VERSION}
    restart: unless-stopped
    <<: *lockdown
    user: ${PUID}:${PGID}
    network_mode: service:gluetun
    volumes:
      - qbittorrent.etc:/qbittorrent/etc
      - qbittorrent.var:/qbittorrent/var
      - media:/media
    environment:
      - TZ=${TZ}
    depends_on:
      gluetun:
        condition: service_healthy
  
  gluetun:
    image: qmcgaw/gluetun:v3.40
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - media-management
      - qbittorrent
    ports:
      - 8001:8000/tcp  # GT Control Server
      - 6881:6881      # QB
      - 6881:6881/udp  # QB
    volumes:
      - gluetun:/gluetun
    environment:
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
### OpenVPN Settings
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
      - SERVER_NAMES=${SERVER_NAMES}
      - OPENVPN_ENDPOINT_IP=${OPENVPN_ENDPOINT_IP}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PROVIDER}
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOG_LEVEL=debug

  gluetun-qbittorrent-port-manager:
    image: snoringdragon/gluetun-qbittorrent-port-manager:latest
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - gluetun:/tmp/gluetun
    environment:
      - QBITTORRENT_SERVER=qbittorrent
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USER=${QBITTORRENT_USER}
      - QBITTORRENT_PASS=${QBITTORRENT_PASS}
      - PORT_FORWARDED=/tmp/gluetun/forwarded_port
      - HTTP_S=http # Select 'http' or 'https' depending on if you use certificates.
      - TZ=${TZ}
    depends_on:
      gluetun:
        condition: service_healthy
